### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by dezashibi** [zebulon75018/flaskretejs#1]
Hi Bro

I cloned your script and installed all requirements\

when I run I got this:
`ImportError: cannot import name 'tabledef' from 'scripts' `

can you help me with this?

**Comment by almereyda** [comment]
Hi @knavels, would you be able to share a word about what helped you close this issue?

I am running into the same error due to the imports in

https://github.com/zebulon75018/flaskretejs/commit/4a1195c03133d85844a8a3665a7ed474797d8fc2#diff-3f41e546893dc64b71aaacad12cad815R3-R5

but cannot resolve it with `pip2 install scripts`.

Eventually @zebulon75018 can shed some light here, about how to satisfy this requirement?

**Comment by zebulon75018** [comment]
Sorry guys ... I haven't seen your notifycation ( covid etc .... ) 
Hum , when I remove the import it doesn t work ... :( but I guess the js change of retejs ... 
thank s for your notification , but I don t know if I have time and energy to fix it.

**Comment by dezashibi** [comment]
Aaaah man, @zebulon75018  ,when you talk about time and energy (which I'm sure it's more about energy rather than time) I know what you mean and I understand you very well
well I myself gave up on this repo in that time, I suggest @almereyda to do the same and find another repo for what you need or share your problem maybe me or @zebulon75018 can direct you to somewhere that would a help for your project

**Comment by zebulon75018** [comment]
Hi ,@knavels  Hum I m thinking if this way is a good way for this project.
Should have to use : 
https://codepen.io/jnanars/pen/azJezp

Or just use 

https://github.com/klauer/qtpynodeeditor and https://github.com/wonderworks-software/PyFlow , and other pakage more mature than my baby projet ;)
what do you think ?
